### ISSUE TITLE
Add initial support for deploying combo through OLM's packaging format

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/combo#71]
Introduce the registry+v1 bundle format manifests that are needed in order to deploy an individual version of the combo-operator through OLM's package format.

Utilize the file-based catalog's format for declarative managing catalogs to help test out any UX challenges around the FBC format.

Add CI checks to ensure that any bundle/catalogs pass static validation using the `opm validate` command, and investigate the usage of [Joe's `opm-validate`](https://github.com/joelanford/opm-validate) github action.

**Comment by tylerslaton** [comment]
Marking this as done as it is:

1. Fairly old
2. Already supported for RukPak which is probably the future of this project.
