### ISSUE TITLE
Combo's version command does not display in container

### ISSUE THREAD

**Issue by tylerslaton** [operator-framework/combo#89]
# Summary
Currently, running Combo's version subcommand when it is build by the `make build-container` target does not display the version information as you would expect:

```console
$ docker run quay.io/operator-framework/combo:latest /bin/combo version
Combo version: 
Git commit: 
Kubernetes version: v0.22.2
```

Running against a locally built binary works just fine:

```console
$ ./bin/combo version
Combo version: v0.0.1
Git commit: 96e188463c006c9781d9947833a3159640aa674c
Kubernetes version: v0.22.2
```

This is most likely because the Git tree is not being brought along when building the container via `make build-container` and thus the version information there is not present.

**Comment by nsapse** [comment]
Closed by PR #91 (https://github.com/operator-framework/combo/pull/91)
